### ISSUE TITLE
[Addon Not Showing Up] <1.12.2> - Addon Not Showing Up In CurseForge Modpack or Minecraft

### ISSUE THREAD

**Issue by CreatingCalifornia** [ProfessorFartsalot/EAS-Addon#5]
**Describe the bug**
I put the addon into the mods folder in the CurseForge modpack im using. After refreshing and restating, the addon still won't show up in the modpack or in Minecraft.

**To Reproduce**
1. Download Addon
2. Place in mod folder in your moadpack
3. Refresh modpack in CurseForge
4. EAS will not show up in CurseForge or in game

**Expected behavior**
The EAS Addon won't show up in a CurseForge Modpack and in-game

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows [e.g. Windows or Linux]
 - Forge Build: 1.12.2-2860
 - Mods: Weather2Remastered@2.8.12  [e.g. Weather2Remastered@2.8.12, CoroUtil@1.2.37]

**Additional context**

**Comment by CosmicHikari** [comment]
I will look into this. Please make sure the mod is actually installed manually and enabled in the curseforge launcher.

I do not build my mods with curseforge compatibility in mind, but I'm sure it should just be a thing of enabling it manually using the mod list menu.

**Comment by CreatingCalifornia** [comment]
Trippel checked everything. It won't even show up in the list of mods on Curse Forge so I can't enable it at all.

**Comment by CosmicHikari** [comment]
The addon is soon to be phased out of support, as @Mrbt0907 will be making it an official component of Weather2 Remastered 2.9 in the weeks to come.
